"""empty message

Revision ID: 0287e41d5bfa
Revises: 3417abd7e494
Create Date: 2022-08-26 17:45:41.126399

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0287e41d5bfa"
down_revision = "3417abd7e494"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
