"""empty message

Revision ID: 100a58518334
Revises: e8c9ef9327b5
Create Date: 2022-10-04 17:34:44.513571

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "100a58518334"
down_revision = "e8c9ef9327b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("training", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "training", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("user_training_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "training_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("training_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("user_training_id_fkey", "user", "training", ["training_id"], ["id"])
    op.drop_constraint(None, "training", type_="foreignkey")
    op.drop_column("training", "user_id")
    # ### end Alembic commands ###
