"""add user model

Revision ID: 3417abd7e494
Revises: 5f910644246f
Create Date: 2022-08-16 16:56:54.397877

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3417abd7e494"
down_revision = "5f910644246f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("training_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["training.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.drop_constraint("exercise_group_id_fkey", "exercise", type_="foreignkey")
    op.create_foreign_key(None, "exercise", "group", ["group_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("set_exercise_id_fkey", "set", type_="foreignkey")
    op.drop_constraint("set_distance_id_fkey", "set", type_="foreignkey")
    op.drop_constraint("set_weight_id_fkey", "set", type_="foreignkey")
    op.drop_constraint("set_training_id_fkey", "set", type_="foreignkey")
    op.create_foreign_key(None, "set", "training", ["training_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "set", "exercise", ["exercise_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "set", "distance", ["distance_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "set", "weight", ["weight_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "set", type_="foreignkey")
    op.drop_constraint(None, "set", type_="foreignkey")
    op.drop_constraint(None, "set", type_="foreignkey")
    op.drop_constraint(None, "set", type_="foreignkey")
    op.create_foreign_key("set_training_id_fkey", "set", "training", ["training_id"], ["id"])
    op.create_foreign_key("set_weight_id_fkey", "set", "weight", ["weight_id"], ["id"])
    op.create_foreign_key("set_distance_id_fkey", "set", "distance", ["distance_id"], ["id"])
    op.create_foreign_key("set_exercise_id_fkey", "set", "exercise", ["exercise_id"], ["id"])
    op.drop_constraint(None, "exercise", type_="foreignkey")
    op.create_foreign_key("exercise_group_id_fkey", "exercise", "group", ["group_id"], ["id"])
    op.drop_table("user")
    # ### end Alembic commands ###
