"""empty message

Revision ID: d3f56bea2c78
Revises: 100a58518334
Create Date: 2022-10-05 15:55:45.009084

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3f56bea2c78"
down_revision = "100a58518334"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("set", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "set", "user", ["added_by"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "set", type_="foreignkey")
    op.drop_column("set", "added_by")
    # ### end Alembic commands ###
