"""empty message

Revision ID: d95caa8d1060
Revises: d3f56bea2c78
Create Date: 2023-06-26 13:54:17.609132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95caa8d1060'
down_revision = 'd3f56bea2c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint('training_user_id_fkey', 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('training', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key('training_user_id_fkey', 'training', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('training', 'created_by')
    # ### end Alembic commands ###
