"""empty message

Revision ID: e8c9ef9327b5
Revises: 0287e41d5bfa
Create Date: 2022-09-14 15:23:57.808993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8c9ef9327b5"
down_revision = "0287e41d5bfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("distance", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "distance", "user", ["added_by"], ["id"], ondelete="SET NULL")
    op.add_column("exercise", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "exercise", "user", ["added_by"], ["id"], ondelete="SET NULL")
    op.add_column("group", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "group", "user", ["added_by"], ["id"], ondelete="SET NULL")
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.add_column("weight", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "weight", "user", ["added_by"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weight", type_="foreignkey")
    op.drop_column("weight", "added_by")
    op.drop_column("user", "is_admin")
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "added_by")
    op.drop_constraint(None, "exercise", type_="foreignkey")
    op.drop_column("exercise", "added_by")
    op.drop_constraint(None, "distance", type_="foreignkey")
    op.drop_column("distance", "added_by")
    # ### end Alembic commands ###
